categories:
  - title: '🚀 Features'
    labels:
      - 'feature ✨'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug 🐜'
  - title: 'payment :moneybag:'
    labels:
      - 'payment :moneybag:'

template: |
  $CHANGES
