name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
    tags:
      - '*'

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: read version and tag
        run: |
         # extract the version from our build file
         echo ::set-env name=VERSION::$(grep versionName $GITHUB_WORKSPACE/app/build.gradle |sed -e 's/^.*versionName "/v/g;s/"//g')
         # if this workflow was launched from a tag, use that tag, otherwise leave the tag blank
         echo ::set-env name=TAG::$([[ $GITHUB_REF == refs/tags/* ]] && echo $GITHUB_REF | sed -e  "s/refs.tags.//g")
      - name: read name
         # the name is the tag if available, otherwise it's the version
         echo ::set-env name=NAME::$([[ $TAG != "" ]] && echo $TAG || echo $NAME)
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ env.TAG }}
          name: ${{ env.NAME }}
          version: ${{ env.VERSION }}
          publish: ${{ startsWith(github.ref, 'refs/tags') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
